export type PhoneSpec = {
  slug: string;
  name: string;
  brand: string;
  short: string;
  priceBand: "Budget" | "Midrange" | "Premium" | "Foldable";
  released: string;
  image: {
    src: string;
    alt: string;
  };
  verifyNote: string;
  scores: {
    camera: number;
    battery: number;
    performance: number;
    longevity: number;
    value: number;
  };
  benchmarks: {
    antutu: string;
    geekbench: string;
    pcmark: string;
    threeDMark: string;
    note: string;
  };
  specs: {
    display: string;
    chipset: string;
    memory: string;
    storage: string;
    rearCamera: string;
    frontCamera: string;
    battery: string;
    charging: string;
    durability: string;
    software: string;
    weight: string;
    extras: string;
  };
  plainEnglish: {
    bestFor: string;
    watchOut: string;
    mamboRead: string;
  };
};

export const scoreLabels: Record<keyof PhoneSpec["scores"], string> = {
  camera: "Camera",
  battery: "Battery",
  performance: "Speed",
  longevity: "Longevity",
  value: "Value"
};

const starterPhones: PhoneSpec[] = [
  {
    slug: "vivo-v40",
    name: "Vivo V40",
    brand: "Vivo",
    short: "Portrait-first midrange phone",
    priceBand: "Midrange",
    released: "2024",
    image: {
      src: "/phones/vivo-v40.jpg",
      alt: "Vivo V40 front and back product image"
    },
    verifyNote: "Verify RAM, storage, and local pricing for the exact Kenya variant.",
    scores: { camera: 8.7, battery: 8.2, performance: 7.4, longevity: 7.2, value: 7.6 },
    benchmarks: {
      antutu: "820K to 900K class",
      geekbench: "1,150 single, 3,300 multi class",
      pcmark: "Work 3.0 varies by variant",
      threeDMark: "Wild Life Extreme entry-mid class",
      note: "Snapdragon 7 Gen 3 results vary by RAM and cooling."
    },
    specs: {
      display: "6.78-inch AMOLED, high refresh rate",
      chipset: "Snapdragon 7 Gen 3 class",
      memory: "8GB or 12GB RAM, market dependent",
      storage: "256GB or 512GB, market dependent",
      rearCamera: "50MP main plus 50MP ultrawide, ZEISS tuning on supported variants",
      frontCamera: "50MP selfie camera",
      battery: "5,500mAh class",
      charging: "80W wired class",
      durability: "IP68 or IP69 class on supported variants",
      software: "Android with Vivo Funtouch OS",
      weight: "Around 190g",
      extras: "Portrait lighting, slim design, camera-led tuning"
    },
    plainEnglish: {
      bestFor: "People who care about portraits, social photos, and a polished hand feel.",
      watchOut: "Not the obvious pick if gaming power and the longest update promise matter most.",
      mamboRead: "A camera-first phone that makes sense when the local price is right."
    }
  },
  {
    slug: "samsung-galaxy-a16-5g",
    name: "Samsung Galaxy A16 5G",
    brand: "Samsung",
    short: "Affordable Samsung with long software support",
    priceBand: "Budget",
    released: "2024",
    image: {
      src: "/phones/samsung-galaxy-a16-5g.jpg",
      alt: "Samsung Galaxy A16 5G front and back product image"
    },
    verifyNote: "Verify local RAM, storage, and warranty before buying.",
    scores: { camera: 6.2, battery: 8.0, performance: 6.3, longevity: 8.5, value: 8.0 },
    benchmarks: {
      antutu: "390K to 460K class",
      geekbench: "700 single, 1,800 multi class",
      pcmark: "Work 3.0 budget class",
      threeDMark: "Not a gaming-focused GPU tier",
      note: "Exact score depends on Exynos or MediaTek market variant."
    },
    specs: {
      display: "6.7-inch AMOLED, 90Hz class",
      chipset: "Entry 5G chipset, market dependent",
      memory: "4GB to 8GB RAM, market dependent",
      storage: "128GB or 256GB, market dependent",
      rearCamera: "50MP main with supporting cameras",
      frontCamera: "13MP class",
      battery: "5,000mAh",
      charging: "25W wired class",
      durability: "Basic dust and splash resistance on supported variants",
      software: "One UI with a long update promise",
      weight: "Around 200g",
      extras: "Samsung ecosystem, microSD on many variants"
    },
    plainEnglish: {
      bestFor: "Buyers who want a safe budget phone with recognizable support.",
      watchOut: "Performance is practical, not exciting.",
      mamboRead: "A sensible phone for people who value updates more than flashy specs."
    }
  },
  {
    slug: "redmi-note-13-pro",
    name: "Redmi Note 13 Pro",
    brand: "Xiaomi",
    short: "Spec-heavy midrange value pick",
    priceBand: "Midrange",
    released: "2024",
    image: {
      src: "/phones/redmi-note-13-pro.jpg",
      alt: "Redmi Note 13 Pro front and back product image"
    },
    verifyNote: "Xiaomi names vary by market. Verify exact 4G or 5G model.",
    scores: { camera: 7.8, battery: 8.0, performance: 7.7, longevity: 6.8, value: 8.5 },
    benchmarks: {
      antutu: "600K to 780K class",
      geekbench: "1,000 single, 2,800 multi class",
      pcmark: "Work 3.0 midrange class",
      threeDMark: "Wild Life Extreme midrange class",
      note: "4G and 5G models use different chipsets."
    },
    specs: {
      display: "AMOLED, high refresh rate",
      chipset: "Snapdragon 7s Gen 2 or market-dependent alternative",
      memory: "8GB or 12GB RAM, market dependent",
      storage: "128GB to 512GB, market dependent",
      rearCamera: "High-megapixel main camera with supporting lenses",
      frontCamera: "16MP class",
      battery: "5,100mAh class",
      charging: "Fast wired charging, variant dependent",
      durability: "Splash resistance on supported variants",
      software: "Android with HyperOS or MIUI lineage",
      weight: "Around 185g",
      extras: "Strong display value, fast charging, spec-forward positioning"
    },
    plainEnglish: {
      bestFor: "People who want a lot of screen and charging spec for the money.",
      watchOut: "Software taste and update confidence vary by buyer and market.",
      mamboRead: "Great value if you are comfortable checking the exact variant."
    }
  },
  {
    slug: "iphone-16",
    name: "iPhone 16",
    brand: "Apple",
    short: "Mainstream iPhone with long support",
    priceBand: "Premium",
    released: "2024",
    image: {
      src: "/phones/iphone-16.jpg",
      alt: "iPhone 16 front and back product image"
    },
    verifyNote: "Verify current local price and storage option.",
    scores: { camera: 8.4, battery: 7.7, performance: 9.0, longevity: 9.2, value: 6.7 },
    benchmarks: {
      antutu: "1.6M to 1.8M class",
      geekbench: "3,200 single, 7,900 multi class",
      pcmark: "Not applicable on iOS",
      threeDMark: "High-end mobile GPU class",
      note: "iOS benchmark suites are not always directly comparable with Android."
    },
    specs: {
      display: "6.1-inch OLED, 60Hz",
      chipset: "Apple A18 class",
      memory: "Apple does not market RAM prominently",
      storage: "128GB, 256GB, or 512GB",
      rearCamera: "48MP main plus ultrawide",
      frontCamera: "12MP TrueDepth class",
      battery: "All-day class, depends on use",
      charging: "USB-C wired and MagSafe wireless",
      durability: "IP68 class",
      software: "iOS with long update support",
      weight: "Around 170g",
      extras: "Apple ecosystem, strong video, long resale life"
    },
    plainEnglish: {
      bestFor: "People who want a reliable phone for years and already like iOS.",
      watchOut: "The 60Hz display feels behind many cheaper Android phones.",
      mamboRead: "Not cheap, but calm, polished, and likely to age well."
    }
  },
  {
    slug: "samsung-galaxy-s24",
    name: "Samsung Galaxy S24",
    brand: "Samsung",
    short: "Compact Android flagship",
    priceBand: "Premium",
    released: "2024",
    image: {
      src: "/phones/samsung-galaxy-s24.jpg",
      alt: "Samsung Galaxy S24 front and back product image"
    },
    verifyNote: "Chipset can vary by market. Verify the local unit.",
    scores: { camera: 8.5, battery: 7.6, performance: 8.8, longevity: 9.3, value: 7.2 },
    benchmarks: {
      antutu: "1.5M to 1.8M class",
      geekbench: "2,000 single, 6,500 multi class",
      pcmark: "Work 3.0 flagship class",
      threeDMark: "Wild Life Extreme flagship class",
      note: "Snapdragon and Exynos versions do not score identically."
    },
    specs: {
      display: "6.2-inch AMOLED, adaptive high refresh rate",
      chipset: "Snapdragon or Exynos flagship class, market dependent",
      memory: "8GB RAM class",
      storage: "128GB or 256GB, market dependent",
      rearCamera: "Triple camera with main, ultrawide, and telephoto",
      frontCamera: "12MP class",
      battery: "4,000mAh class",
      charging: "25W wired class plus wireless",
      durability: "IP68 class",
      software: "One UI with long update support",
      weight: "Around 167g",
      extras: "Galaxy AI features, compact flagship size"
    },
    plainEnglish: {
      bestFor: "People who want flagship power without a huge phone.",
      watchOut: "Charging speed and battery size are not the headline strengths.",
      mamboRead: "A strong all-rounder if compact size matters."
    }
  },
  {
    slug: "samsung-galaxy-z-fold6",
    name: "Samsung Galaxy Z Fold6",
    brand: "Samsung",
    short: "Big-screen foldable productivity phone",
    priceBand: "Foldable",
    released: "2024",
    image: {
      src: "/phones/samsung-galaxy-z-fold6.jpg",
      alt: "Samsung Galaxy Z Fold6 front and back product image"
    },
    verifyNote: "Verify repair pricing, warranty, and local availability.",
    scores: { camera: 8.0, battery: 7.2, performance: 9.1, longevity: 8.5, value: 5.8 },
    benchmarks: {
      antutu: "1.8M to 2.1M class",
      geekbench: "2,200 single, 6,900 multi class",
      pcmark: "Work 3.0 flagship foldable class",
      threeDMark: "Wild Life Extreme flagship class",
      note: "Foldable thermals can affect long gaming runs."
    },
    specs: {
      display: "Outer phone screen plus large inner folding AMOLED",
      chipset: "Snapdragon flagship class",
      memory: "12GB RAM class",
      storage: "256GB to 1TB, market dependent",
      rearCamera: "Triple camera system",
      frontCamera: "Cover and inner selfie cameras",
      battery: "4,400mAh class",
      charging: "25W wired class plus wireless",
      durability: "IP48 class on supported model",
      software: "One UI with foldable multitasking features",
      weight: "Around 239g",
      extras: "Split screen, tablet-like canvas, S Pen support on inner display"
    },
    plainEnglish: {
      bestFor: "People who read, multitask, edit, or work from their phone.",
      watchOut: "Expensive, heavier, and repair stakes are higher.",
      mamboRead: "Brilliant if the big screen solves a real daily problem."
    }
  },
  {
    slug: "tecno-spark-30",
    name: "Tecno Spark 30",
    brand: "Tecno",
    short: "Budget phone for everyday basics",
    priceBand: "Budget",
    released: "2024",
    image: {
      src: "/phones/tecno-spark-30.jpg",
      alt: "Tecno Spark 30 front and back product image"
    },
    verifyNote: "Verify exact local model, RAM, storage, and price.",
    scores: { camera: 5.9, battery: 8.1, performance: 5.8, longevity: 5.9, value: 8.3 },
    benchmarks: {
      antutu: "250K to 430K class",
      geekbench: "400 to 750 single, 1,300 to 2,000 multi class",
      pcmark: "Work 3.0 budget class",
      threeDMark: "Not a gaming-focused GPU tier",
      note: "Spark model names vary heavily by market."
    },
    specs: {
      display: "Large LCD or AMOLED depending on exact model",
      chipset: "Entry to lower-mid chipset, variant dependent",
      memory: "4GB to 8GB RAM, market dependent",
      storage: "128GB or 256GB, market dependent",
      rearCamera: "High-megapixel main camera, variant dependent",
      frontCamera: "Selfie camera, variant dependent",
      battery: "5,000mAh class",
      charging: "Wired charging, variant dependent",
      durability: "Basic everyday durability",
      software: "Android with Tecno HiOS",
      weight: "Around 190g to 200g",
      extras: "Big screen, budget positioning, local familiarity"
    },
    plainEnglish: {
      bestFor: "Budget buyers who need WhatsApp, calls, video, and battery.",
      watchOut: "Performance and update support are the main compromises.",
      mamboRead: "A basics-first choice if the verified price is low enough."
    }
  },
  {
    slug: "infinix-hot-50",
    name: "Infinix Hot 50",
    brand: "Infinix",
    short: "Large-screen budget entertainment phone",
    priceBand: "Budget",
    released: "2024",
    image: {
      src: "/phones/infinix-hot-50.jpg",
      alt: "Infinix Hot 50 front and back product image"
    },
    verifyNote: "Verify exact 4G or 5G model before comparing.",
    scores: { camera: 5.8, battery: 8.0, performance: 6.2, longevity: 5.8, value: 8.2 },
    benchmarks: {
      antutu: "300K to 460K class",
      geekbench: "650 single, 1,900 multi class",
      pcmark: "Work 3.0 budget class",
      threeDMark: "Not a gaming-focused GPU tier",
      note: "4G and 5G versions should be compared separately."
    },
    specs: {
      display: "Large high-refresh display, variant dependent",
      chipset: "Entry to lower-mid chipset, variant dependent",
      memory: "4GB to 8GB RAM, market dependent",
      storage: "128GB or 256GB, market dependent",
      rearCamera: "Main camera with supporting sensors",
      frontCamera: "Selfie camera, variant dependent",
      battery: "5,000mAh class",
      charging: "Wired charging, variant dependent",
      durability: "Basic everyday durability",
      software: "Android with Infinix XOS",
      weight: "Around 190g to 200g",
      extras: "Large display, entertainment focus, value pricing"
    },
    plainEnglish: {
      bestFor: "People who want a big screen and long battery for less.",
      watchOut: "Camera and software polish are not flagship-level.",
      mamboRead: "Good value when the exact variant has enough RAM and storage."
    }
  }
];

type RecentPhoneSeed = {
  slug: string;
  name: string;
  brand: string;
  short: string;
  priceBand: PhoneSpec["priceBand"];
  released: string;
  image: PhoneSpec["image"];
  verifyNote?: string;
  scores: PhoneSpec["scores"];
  benchmarks: PhoneSpec["benchmarks"];
  display: string;
  chipset: string;
  memory: string;
  storage: string;
  rearCamera: string;
  frontCamera: string;
  battery: string;
  charging: string;
  durability: string;
  software: string;
  weight: string;
  extras: string;
  bestFor: string;
  watchOut: string;
  mamboRead: string;
};

const gsmImage = (file: string) => `https://fdn2.gsmarena.com/vv/bigpic/${file}.jpg`;

function recentPhone(seed: RecentPhoneSeed): PhoneSpec {
  return {
    slug: seed.slug,
    name: seed.name,
    brand: seed.brand,
    short: seed.short,
    priceBand: seed.priceBand,
    released: seed.released,
    image: seed.image,
    verifyNote: seed.verifyNote ?? "Verify exact regional variant, storage tier, and current local pricing before buying.",
    scores: seed.scores,
    benchmarks: seed.benchmarks,
    specs: {
      display: seed.display,
      chipset: seed.chipset,
      memory: seed.memory,
      storage: seed.storage,
      rearCamera: seed.rearCamera,
      frontCamera: seed.frontCamera,
      battery: seed.battery,
      charging: seed.charging,
      durability: seed.durability,
      software: seed.software,
      weight: seed.weight,
      extras: seed.extras
    },
    plainEnglish: {
      bestFor: seed.bestFor,
      watchOut: seed.watchOut,
      mamboRead: seed.mamboRead
    }
  };
}

const majorRecentPhones: PhoneSpec[] = [
  recentPhone({
    slug: "samsung-galaxy-s26-ultra",
    name: "Samsung Galaxy S26 Ultra",
    brand: "Samsung",
    short: "Big Galaxy flagship with S Pen",
    priceBand: "Premium",
    released: "2026",
    image: { src: gsmImage("samsung-galaxy-s26-ultra-new"), alt: "Samsung Galaxy S26 Ultra product image" },
    scores: { camera: 9.4, battery: 8.5, performance: 9.7, longevity: 9.5, value: 6.8 },
    benchmarks: {
      antutu: "3.0M plus class",
      geekbench: "3,000 plus single, 9,000 plus multi class",
      pcmark: "Work 3.0 elite Android class",
      threeDMark: "Elite Android GPU class",
      note: "Early and regional scores can shift after firmware updates."
    },
    display: "Large LTPO AMOLED, adaptive high refresh rate",
    chipset: "Latest Snapdragon flagship class, market dependent",
    memory: "12GB RAM class or higher",
    storage: "256GB to 1TB class",
    rearCamera: "Multi-camera flagship system with periscope zoom",
    frontCamera: "12MP class",
    battery: "5,000mAh class",
    charging: "Fast wired plus wireless charging",
    durability: "IP68 class",
    software: "One UI with long update support",
    weight: "Heavy flagship class",
    extras: "S Pen, Galaxy AI, premium zoom camera",
    bestFor: "People who want the biggest Samsung camera and productivity package.",
    watchOut: "The price and size are the main compromises.",
    mamboRead: "A no-compromise Android flagship if budget is not the first filter."
  }),
  recentPhone({
    slug: "oneplus-15",
    name: "OnePlus 15",
    brand: "OnePlus",
    short: "Performance-first Android flagship",
    priceBand: "Premium",
    released: "2026",
    image: { src: gsmImage("oneplus-15"), alt: "OnePlus 15 product image" },
    scores: { camera: 8.5, battery: 9.1, performance: 9.7, longevity: 8.4, value: 7.7 },
    benchmarks: {
      antutu: "3.0M plus class",
      geekbench: "3,000 plus single, 9,000 plus multi class",
      pcmark: "Work 3.0 elite Android class",
      threeDMark: "Elite Android GPU class",
      note: "Performance mode can change peak scores substantially."
    },
    display: "Large LTPO AMOLED, high refresh rate",
    chipset: "Latest Snapdragon flagship class",
    memory: "12GB or 16GB RAM class",
    storage: "256GB to 1TB class",
    rearCamera: "Triple flagship camera system",
    frontCamera: "High-resolution selfie camera",
    battery: "Large flagship battery class",
    charging: "Very fast wired charging, wireless on supported variants",
    durability: "Flagship ingress protection, variant dependent",
    software: "Android with OxygenOS",
    weight: "Around 200g plus class",
    extras: "Fast charging, high sustained performance",
    bestFor: "Buyers who care about speed, battery, and charging more than brand prestige.",
    watchOut: "Camera consistency should be checked against Samsung, Apple, and Pixel.",
    mamboRead: "A power-user flagship built around speed and endurance."
  }),
  recentPhone({
    slug: "samsung-galaxy-s25-ultra",
    name: "Samsung Galaxy S25 Ultra",
    brand: "Samsung",
    short: "S Pen flagship with long support",
    priceBand: "Premium",
    released: "2025",
    image: { src: gsmImage("samsung-galaxy-s25-ultra-sm-s938"), alt: "Samsung Galaxy S25 Ultra product image" },
    scores: { camera: 9.3, battery: 8.4, performance: 9.5, longevity: 9.5, value: 6.9 },
    benchmarks: {
      antutu: "2.4M to 2.8M class",
      geekbench: "2,900 single, 9,000 multi class",
      pcmark: "Work 3.0 elite Android class",
      threeDMark: "Wild Life Extreme elite class",
      note: "Snapdragon for Galaxy results vary by thermals and test version."
    },
    display: "6.9-inch LTPO AMOLED, adaptive high refresh rate",
    chipset: "Snapdragon 8 Elite for Galaxy class",
    memory: "12GB RAM class",
    storage: "256GB to 1TB",
    rearCamera: "Quad camera with high-resolution main and periscope zoom",
    frontCamera: "12MP class",
    battery: "5,000mAh class",
    charging: "45W wired class plus wireless",
    durability: "IP68 class",
    software: "One UI with long update support",
    weight: "Around 218g",
    extras: "S Pen, Galaxy AI, strong zoom versatility",
    bestFor: "People who want one phone for camera, work, notes, and years of updates.",
    watchOut: "Charging speed is still conservative for the price.",
    mamboRead: "The safest ultra-premium Android pick for most power users."
  }),
  recentPhone({
    slug: "iphone-16-pro-max",
    name: "iPhone 16 Pro Max",
    brand: "Apple",
    short: "Largest Pro iPhone",
    priceBand: "Premium",
    released: "2024",
    image: { src: gsmImage("apple-iphone-16-pro-max"), alt: "iPhone 16 Pro Max product image" },
    scores: { camera: 9.2, battery: 8.8, performance: 9.6, longevity: 9.4, value: 6.5 },
    benchmarks: {
      antutu: "1.8M to 2.0M class",
      geekbench: "3,400 single, 8,500 multi class",
      pcmark: "Not applicable on iOS",
      threeDMark: "High-end iOS GPU class",
      note: "iOS and Android benchmark totals should not be compared one-to-one."
    },
    display: "6.9-inch LTPO OLED, 120Hz",
    chipset: "Apple A18 Pro class",
    memory: "Apple does not market RAM prominently",
    storage: "256GB to 1TB",
    rearCamera: "48MP main, ultrawide, and telephoto system",
    frontCamera: "12MP TrueDepth class",
    battery: "Long iPhone battery life class",
    charging: "USB-C wired and MagSafe wireless",
    durability: "IP68 class",
    software: "iOS with long update support",
    weight: "Around 227g",
    extras: "Strong video, Apple ecosystem, premium resale",
    bestFor: "Creators, iOS users, and anyone who wants a polished long-term phone.",
    watchOut: "Very expensive, and charging remains slower than many Android rivals.",
    mamboRead: "The big iPhone to buy when video, battery, and resale matter."
  }),
  recentPhone({
    slug: "google-pixel-9-pro-xl",
    name: "Google Pixel 9 Pro XL",
    brand: "Google",
    short: "Large Pixel camera flagship",
    priceBand: "Premium",
    released: "2024",
    image: { src: gsmImage("google-pixel-9-pro-xl-"), alt: "Google Pixel 9 Pro XL product image" },
    scores: { camera: 9.1, battery: 7.8, performance: 8.1, longevity: 9.3, value: 7.0 },
    benchmarks: {
      antutu: "1.1M to 1.3M class",
      geekbench: "1,900 single, 4,600 multi class",
      pcmark: "Work 3.0 upper-mid to flagship class",
      threeDMark: "Below Snapdragon flagship GPU tier",
      note: "Tensor phones prioritize AI and camera pipeline more than peak GPU scores."
    },
    display: "Large LTPO OLED, high refresh rate",
    chipset: "Google Tensor G4 class",
    memory: "16GB RAM class",
    storage: "128GB to 1TB, market dependent",
    rearCamera: "Triple camera with telephoto",
    frontCamera: "High-resolution selfie camera",
    battery: "5,000mAh class",
    charging: "Fast wired plus wireless charging",
    durability: "IP68 class",
    software: "Pixel Android with long update support",
    weight: "Around 220g",
    extras: "Pixel AI, clean Android, strong still photos",
    bestFor: "People who want point-and-shoot photos and Google software first.",
    watchOut: "Raw gaming performance trails the fastest Snapdragon phones.",
    mamboRead: "A camera and software phone before it is a benchmark phone."
  }),
  recentPhone({
    slug: "oneplus-13",
    name: "OnePlus 13",
    brand: "OnePlus",
    short: "Fast-charging flagship",
    priceBand: "Premium",
    released: "2025",
    image: { src: gsmImage("oneplus-13"), alt: "OnePlus 13 product image" },
    scores: { camera: 8.5, battery: 9.2, performance: 9.5, longevity: 8.4, value: 7.9 },
    benchmarks: {
      antutu: "2.5M to 2.9M class",
      geekbench: "3,000 single, 9,000 multi class",
      pcmark: "Work 3.0 elite Android class",
      threeDMark: "Wild Life Extreme elite class",
      note: "Scores are strongest in performance mode."
    },
    display: "Large LTPO AMOLED, high refresh rate",
    chipset: "Snapdragon 8 Elite class",
    memory: "12GB or 16GB RAM class",
    storage: "256GB to 1TB class",
    rearCamera: "Triple camera with Hasselblad tuning",
    frontCamera: "32MP class",
    battery: "6,000mAh class",
    charging: "Very fast wired and wireless charging",
    durability: "IP68 or IP69 class on supported variants",
    software: "Android with OxygenOS",
    weight: "Around 210g",
    extras: "Large battery, fast charging, flagship chip",
    bestFor: "People who want flagship speed and unusually strong battery.",
    watchOut: "Camera taste still differs from Pixel, iPhone, and Galaxy.",
    mamboRead: "One of the strongest Android choices when charging and battery are high priorities."
  }),
  recentPhone({
    slug: "xiaomi-14-ultra",
    name: "Xiaomi 14 Ultra",
    brand: "Xiaomi",
    short: "Photography-first Android flagship",
    priceBand: "Premium",
    released: "2024",
    image: { src: gsmImage("xiaomi-14-ultra-new"), alt: "Xiaomi 14 Ultra product image" },
    scores: { camera: 9.3, battery: 8.2, performance: 9.2, longevity: 7.8, value: 7.2 },
    benchmarks: {
      antutu: "1.9M to 2.1M class",
      geekbench: "2,200 single, 6,900 multi class",
      pcmark: "Work 3.0 flagship class",
      threeDMark: "Wild Life Extreme flagship class",
      note: "Camera kit and regional software can affect the overall experience."
    },
    display: "Large LTPO AMOLED, high refresh rate",
    chipset: "Snapdragon 8 Gen 3 class",
    memory: "12GB or 16GB RAM class",
    storage: "256GB to 1TB class",
    rearCamera: "Quad Leica camera system",
    frontCamera: "32MP class",
    battery: "5,000mAh class",
    charging: "Very fast wired plus wireless charging",
    durability: "IP68 class",
    software: "Android with HyperOS",
    weight: "Around 220g",
    extras: "Large sensor camera, Leica tuning, optional camera grip ecosystem",
    bestFor: "People who care deeply about mobile photography hardware.",
    watchOut: "Software preference and local warranty matter a lot.",
    mamboRead: "A camera-led flagship for buyers who enjoy tuning shots."
  }),
  recentPhone({
    slug: "samsung-galaxy-s24-ultra",
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    short: "S Pen flagship from 2024",
    priceBand: "Premium",
    released: "2024",
    image: { src: gsmImage("samsung-galaxy-s24-ultra-5g-sm-s928-stylus"), alt: "Samsung Galaxy S24 Ultra product image" },
    scores: { camera: 9.1, battery: 8.3, performance: 9.2, longevity: 9.4, value: 7.1 },
    benchmarks: {
      antutu: "1.8M to 2.1M class",
      geekbench: "2,200 single, 6,900 multi class",
      pcmark: "Work 3.0 flagship class",
      threeDMark: "Wild Life Extreme flagship class",
      note: "Snapdragon for Galaxy scores are strong but thermal state matters."
    },
    display: "6.8-inch LTPO AMOLED, 120Hz",
    chipset: "Snapdragon 8 Gen 3 for Galaxy class",
    memory: "12GB RAM class",
    storage: "256GB to 1TB",
    rearCamera: "Quad camera with high-resolution main and zoom lenses",
    frontCamera: "12MP class",
    battery: "5,000mAh",
    charging: "45W wired class plus wireless",
    durability: "IP68 class, titanium frame",
    software: "One UI with long update support",
    weight: "Around 232g",
    extras: "S Pen, Galaxy AI, anti-reflective display",
    bestFor: "People who want an Ultra phone but can find 2024 pricing.",
    watchOut: "Still big, heavy, and premium-priced.",
    mamboRead: "A strong buy when discounted below newer Ultra models."
  }),
  recentPhone({
    slug: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    short: "Titanium iPhone with 5x zoom",
    priceBand: "Premium",
    released: "2023",
    image: { src: gsmImage("apple-iphone-15-pro-max"), alt: "iPhone 15 Pro Max product image" },
    scores: { camera: 8.9, battery: 8.5, performance: 9.2, longevity: 9.1, value: 6.9 },
    benchmarks: {
      antutu: "1.5M to 1.7M class",
      geekbench: "2,900 single, 7,200 multi class",
      pcmark: "Not applicable on iOS",
      threeDMark: "High-end iOS GPU class",
      note: "A17 Pro thermal behavior depends heavily on workload duration."
    },
    display: "6.7-inch LTPO OLED, 120Hz",
    chipset: "Apple A17 Pro class",
    memory: "Apple does not market RAM prominently",
    storage: "256GB to 1TB",
    rearCamera: "48MP main, ultrawide, and 5x telephoto",
    frontCamera: "12MP TrueDepth class",
    battery: "Long iPhone battery life class",
    charging: "USB-C wired and MagSafe wireless",
    durability: "IP68 class, titanium frame",
    software: "iOS with long update support",
    weight: "Around 221g",
    extras: "USB-C, strong video, high resale",
    bestFor: "iOS users who want a Pro Max without paying current top prices.",
    watchOut: "It can still be costly on the used and refurbished market.",
    mamboRead: "Still a premium iPhone with years of useful life left."
  }),
  recentPhone({
    slug: "google-pixel-8-pro",
    name: "Google Pixel 8 Pro",
    brand: "Google",
    short: "AI-heavy Pixel flagship",
    priceBand: "Premium",
    released: "2023",
    image: { src: gsmImage("google-pixel-8-pro"), alt: "Google Pixel 8 Pro product image" },
    scores: { camera: 8.9, battery: 7.4, performance: 7.8, longevity: 9.1, value: 7.2 },
    benchmarks: {
      antutu: "900K to 1.1M class",
      geekbench: "1,700 single, 4,300 multi class",
      pcmark: "Work 3.0 upper-mid to flagship class",
      threeDMark: "Below Snapdragon flagship GPU tier",
      note: "Tensor G3 is stronger at camera and AI features than raw gaming."
    },
    display: "6.7-inch LTPO OLED, 120Hz",
    chipset: "Google Tensor G3 class",
    memory: "12GB RAM class",
    storage: "128GB to 1TB, market dependent",
    rearCamera: "Triple camera with telephoto",
    frontCamera: "10.5MP class",
    battery: "5,050mAh class",
    charging: "Fast wired plus wireless charging",
    durability: "IP68 class",
    software: "Pixel Android with long update support",
    weight: "Around 213g",
    extras: "Pixel AI tools, excellent still photography",
    bestFor: "People who want Pixel photos and long software support for less.",
    watchOut: "Battery and sustained gaming are not top of class.",
    mamboRead: "A smart discounted camera phone if you value Google software."
  }),
  recentPhone({
    slug: "samsung-galaxy-s23-ultra",
    name: "Samsung Galaxy S23 Ultra",
    brand: "Samsung",
    short: "Older Ultra still worth comparing",
    priceBand: "Premium",
    released: "2023",
    image: { src: gsmImage("samsung-galaxy-s23-ultra-5g"), alt: "Samsung Galaxy S23 Ultra product image" },
    scores: { camera: 8.8, battery: 8.2, performance: 8.8, longevity: 8.4, value: 7.4 },
    benchmarks: {
      antutu: "1.4M to 1.6M class",
      geekbench: "1,900 single, 5,100 multi class",
      pcmark: "Work 3.0 flagship class",
      threeDMark: "Wild Life Extreme flagship class",
      note: "Still fast, though newer Snapdragon Elite devices are much quicker."
    },
    display: "6.8-inch AMOLED, 120Hz",
    chipset: "Snapdragon 8 Gen 2 for Galaxy class",
    memory: "8GB or 12GB RAM class",
    storage: "256GB to 1TB",
    rearCamera: "Quad camera with 200MP main and zoom lenses",
    frontCamera: "12MP class",
    battery: "5,000mAh",
    charging: "45W wired class plus wireless",
    durability: "IP68 class",
    software: "One UI with ongoing support",
    weight: "Around 234g",
    extras: "S Pen, strong zoom, mature pricing",
    bestFor: "Buyers who want Ultra features at a lower used or discounted price.",
    watchOut: "Update runway is shorter than newer Galaxy flagships.",
    mamboRead: "A capable Ultra if the price has dropped enough."
  }),
  recentPhone({
    slug: "oneplus-12",
    name: "OnePlus 12",
    brand: "OnePlus",
    short: "Fast flagship value",
    priceBand: "Premium",
    released: "2024",
    image: { src: gsmImage("oneplus-12"), alt: "OnePlus 12 product image" },
    scores: { camera: 8.2, battery: 9.0, performance: 9.2, longevity: 8.0, value: 8.0 },
    benchmarks: {
      antutu: "1.8M to 2.1M class",
      geekbench: "2,200 single, 6,900 multi class",
      pcmark: "Work 3.0 flagship class",
      threeDMark: "Wild Life Extreme flagship class",
      note: "A strong Snapdragon 8 Gen 3 implementation."
    },
    display: "Large LTPO AMOLED, high refresh rate",
    chipset: "Snapdragon 8 Gen 3 class",
    memory: "12GB or 16GB RAM class",
    storage: "256GB to 512GB class",
    rearCamera: "Triple camera with Hasselblad tuning",
    frontCamera: "32MP class",
    battery: "5,400mAh class",
    charging: "Very fast wired plus wireless charging",
    durability: "Splash resistance on supported variants",
    software: "Android with OxygenOS",
    weight: "Around 220g",
    extras: "Bright screen, fast charging, strong performance",
    bestFor: "People who want a flagship chip and battery without Samsung pricing.",
    watchOut: "Ingress protection and camera preference vary by region and buyer.",
    mamboRead: "One of the better performance-value flagships from 2024."
  }),
  recentPhone({
    slug: "oneplus-11",
    name: "OnePlus 11",
    brand: "OnePlus",
    short: "Discount flagship performer",
    priceBand: "Premium",
    released: "2023",
    image: { src: gsmImage("oneplus-11"), alt: "OnePlus 11 product image" },
    scores: { camera: 7.8, battery: 8.1, performance: 8.8, longevity: 7.5, value: 8.0 },
    benchmarks: {
      antutu: "1.3M to 1.5M class",
      geekbench: "1,700 single, 4,900 multi class",
      pcmark: "Work 3.0 flagship class",
      threeDMark: "Wild Life Extreme flagship class",
      note: "Older flagship chip, still fast for most users."
    },
    display: "Large AMOLED, 120Hz class",
    chipset: "Snapdragon 8 Gen 2 class",
    memory: "8GB to 16GB RAM class",
    storage: "128GB to 512GB class",
    rearCamera: "Triple camera with Hasselblad tuning",
    frontCamera: "16MP class",
    battery: "5,000mAh",
    charging: "Very fast wired charging",
    durability: "Basic splash resistance, variant dependent",
    software: "Android with OxygenOS",
    weight: "Around 205g",
    extras: "Fast charging, flagship chip, lower current pricing",
    bestFor: "Buyers hunting older flagship speed for less money.",
    watchOut: "No wireless charging and shorter update runway than newer models.",
    mamboRead: "A good bargain flagship if the battery health and warranty check out."
  }),
  recentPhone({
    slug: "xiaomi-13-ultra",
    name: "Xiaomi 13 Ultra",
    brand: "Xiaomi",
    short: "Leica camera flagship",
    priceBand: "Premium",
    released: "2023",
    image: { src: gsmImage("xiaomi-13-ultra"), alt: "Xiaomi 13 Ultra product image" },
    scores: { camera: 9.1, battery: 7.9, performance: 8.8, longevity: 7.3, value: 7.0 },
    benchmarks: {
      antutu: "1.4M to 1.6M class",
      geekbench: "1,900 single, 5,200 multi class",
      pcmark: "Work 3.0 flagship class",
      threeDMark: "Wild Life Extreme flagship class",
      note: "Older Snapdragon flagship with camera-led design."
    },
    display: "Large LTPO AMOLED, 120Hz",
    chipset: "Snapdragon 8 Gen 2 class",
    memory: "12GB or 16GB RAM class",
    storage: "256GB to 1TB class",
    rearCamera: "Quad Leica camera system",
    frontCamera: "32MP class",
    battery: "5,000mAh",
    charging: "Fast wired plus wireless charging",
    durability: "IP68 class",
    software: "Android with MIUI or HyperOS lineage",
    weight: "Around 227g",
    extras: "Large sensor camera hardware, Leica tuning",
    bestFor: "Photo-focused buyers considering older flagship pricing.",
    watchOut: "Import status, warranty, and software updates need checking.",
    mamboRead: "Still compelling when photography is the main reason to buy."
  }),
  recentPhone({
    slug: "google-pixel-9a",
    name: "Google Pixel 9a",
    brand: "Google",
    short: "Affordable Pixel with long support",
    priceBand: "Midrange",
    released: "2025",
    image: { src: gsmImage("google-pixel-9a"), alt: "Google Pixel 9a product image" },
    scores: { camera: 8.0, battery: 8.0, performance: 7.5, longevity: 9.0, value: 8.0 },
    benchmarks: {
      antutu: "900K to 1.1M class",
      geekbench: "1,700 single, 4,300 multi class",
      pcmark: "Work 3.0 upper-mid class",
      threeDMark: "Below Snapdragon flagship GPU tier",
      note: "Tensor scores are enough for daily use, not aimed at gaming charts."
    },
    display: "OLED, high refresh rate",
    chipset: "Google Tensor class, generation dependent",
    memory: "8GB RAM class",
    storage: "128GB or 256GB",
    rearCamera: "Dual Pixel camera system",
    frontCamera: "Selfie camera class",
    battery: "Large Pixel A-series battery class",
    charging: "Wired charging, wireless on supported model",
    durability: "IP rating on supported model",
    software: "Pixel Android with long update support",
    weight: "Midweight class",
    extras: "Pixel camera processing, clean Android",
    bestFor: "People who want Pixel software without flagship pricing.",
    watchOut: "Gaming performance and charging are not the main appeal.",
    mamboRead: "The practical Pixel for buyers who value updates and photos."
  }),
  recentPhone({
    slug: "google-pixel-8a",
    name: "Google Pixel 8a",
    brand: "Google",
    short: "Compact Pixel value phone",
    priceBand: "Midrange",
    released: "2024",
    image: { src: gsmImage("google-pixel-8a"), alt: "Google Pixel 8a product image" },
    scores: { camera: 7.8, battery: 7.3, performance: 7.5, longevity: 8.9, value: 8.1 },
    benchmarks: {
      antutu: "850K to 1.0M class",
      geekbench: "1,700 single, 4,300 multi class",
      pcmark: "Work 3.0 upper-mid class",
      threeDMark: "Below Snapdragon flagship GPU tier",
      note: "A-series Pixels favor camera and update support over peak speed."
    },
    display: "6.1-inch OLED, high refresh rate",
    chipset: "Google Tensor G3 class",
    memory: "8GB RAM class",
    storage: "128GB or 256GB",
    rearCamera: "Dual camera system",
    frontCamera: "13MP class",
    battery: "4,492mAh class",
    charging: "Wired plus wireless charging",
    durability: "IP67 class",
    software: "Pixel Android with long update support",
    weight: "Around 188g",
    extras: "Pixel AI tools, compact size",
    bestFor: "Buyers who want a smaller Pixel with long software support.",
    watchOut: "Charging and sustained performance are modest.",
    mamboRead: "A good-value Pixel when discounted."
  }),
  recentPhone({
    slug: "samsung-galaxy-a55-5g",
    name: "Samsung Galaxy A55 5G",
    brand: "Samsung",
    short: "Upper-midrange Galaxy",
    priceBand: "Midrange",
    released: "2024",
    image: { src: gsmImage("samsung-galaxy-a55"), alt: "Samsung Galaxy A55 5G product image" },
    scores: { camera: 7.3, battery: 8.2, performance: 7.2, longevity: 8.2, value: 8.0 },
    benchmarks: {
      antutu: "700K to 750K class",
      geekbench: "1,100 single, 3,400 multi class",
      pcmark: "Work 3.0 midrange class",
      threeDMark: "Midrange GPU class",
      note: "A balanced midrange chip, not a gaming flagship."
    },
    display: "6.6-inch AMOLED, 120Hz class",
    chipset: "Exynos 1480 class",
    memory: "8GB or 12GB RAM, market dependent",
    storage: "128GB or 256GB",
    rearCamera: "50MP main with ultrawide and macro",
    frontCamera: "32MP class",
    battery: "5,000mAh",
    charging: "25W wired class",
    durability: "IP67 class",
    software: "One UI with long midrange support",
    weight: "Around 213g",
    extras: "Samsung ecosystem, strong build, microSD on supported variants",
    bestFor: "People who want a dependable Samsung without flagship pricing.",
    watchOut: "Charging speed and gaming power trail some Chinese rivals.",
    mamboRead: "A steady midrange phone that wins on trust and support."
  }),
  recentPhone({
    slug: "nothing-phone-2a",
    name: "Nothing Phone 2a",
    brand: "Nothing",
    short: "Design-forward midrange phone",
    priceBand: "Midrange",
    released: "2024",
    image: { src: gsmImage("nothing-phone-2a"), alt: "Nothing Phone 2a product image" },
    scores: { camera: 7.0, battery: 8.4, performance: 7.1, longevity: 7.7, value: 8.2 },
    benchmarks: {
      antutu: "700K class",
      geekbench: "1,100 single, 2,600 multi class",
      pcmark: "Work 3.0 midrange class",
      threeDMark: "Midrange GPU class",
      note: "Dimensity 7200 Pro class scores suit daily use and light gaming."
    },
    display: "Large AMOLED, 120Hz class",
    chipset: "MediaTek Dimensity 7200 Pro class",
    memory: "8GB or 12GB RAM class",
    storage: "128GB or 256GB",
    rearCamera: "Dual 50MP camera system",
    frontCamera: "32MP class",
    battery: "5,000mAh",
    charging: "Fast wired charging",
    durability: "IP54 class",
    software: "Nothing OS on Android",
    weight: "Around 190g",
    extras: "Glyph lights, clean software, distinctive design",
    bestFor: "People who want style and clean software in the midrange.",
    watchOut: "Camera and chipset are not flagship-level.",
    mamboRead: "A personality pick that still makes practical sense."
  }),
  recentPhone({
    slug: "oneplus-open",
    name: "OnePlus Open",
    brand: "OnePlus",
    short: "Slim book-style foldable",
    priceBand: "Foldable",
    released: "2023",
    image: { src: gsmImage("oneplus-open-10"), alt: "OnePlus Open product image" },
    scores: { camera: 8.4, battery: 7.9, performance: 8.8, longevity: 7.5, value: 6.8 },
    benchmarks: {
      antutu: "1.4M to 1.6M class",
      geekbench: "1,900 single, 5,100 multi class",
      pcmark: "Work 3.0 flagship foldable class",
      threeDMark: "Wild Life Extreme flagship class",
      note: "Foldable body design can affect sustained thermal behavior."
    },
    display: "Outer phone display plus large inner folding AMOLED",
    chipset: "Snapdragon 8 Gen 2 class",
    memory: "16GB RAM class",
    storage: "512GB class",
    rearCamera: "Triple Hasselblad camera system",
    frontCamera: "Cover and inner selfie cameras",
    battery: "4,805mAh class",
    charging: "Fast wired charging",
    durability: "Foldable durability class",
    software: "Android with Open Canvas multitasking",
    weight: "Around 239g",
    extras: "Excellent multitasking layout, slim foldable design",
    bestFor: "People who want a foldable for reading, work, and multitasking.",
    watchOut: "Repair, warranty, and dust protection matter more than on a slab phone.",
    mamboRead: "One of the most practical foldables if productivity is the goal."
  }),
  recentPhone({
    slug: "samsung-galaxy-z-fold5",
    name: "Samsung Galaxy Z Fold5",
    brand: "Samsung",
    short: "Mature Samsung foldable",
    priceBand: "Foldable",
    released: "2023",
    image: { src: gsmImage("samsung-galaxy-z-fold5-5g"), alt: "Samsung Galaxy Z Fold5 product image" },
    scores: { camera: 7.8, battery: 7.1, performance: 8.7, longevity: 8.0, value: 6.2 },
    benchmarks: {
      antutu: "1.3M to 1.5M class",
      geekbench: "1,800 single, 5,000 multi class",
      pcmark: "Work 3.0 flagship foldable class",
      threeDMark: "Wild Life Extreme flagship class",
      note: "Older foldable flagship, still powerful but price-sensitive."
    },
    display: "Outer screen plus large inner folding AMOLED",
    chipset: "Snapdragon 8 Gen 2 for Galaxy class",
    memory: "12GB RAM class",
    storage: "256GB to 1TB",
    rearCamera: "Triple camera system",
    frontCamera: "Cover and inner selfie cameras",
    battery: "4,400mAh class",
    charging: "25W wired class plus wireless",
    durability: "IPX8 class",
    software: "One UI foldable multitasking",
    weight: "Around 253g",
    extras: "S Pen support, mature foldable software",
    bestFor: "Samsung users who want foldable productivity at lower pricing.",
    watchOut: "It is heavier and less refined than newer foldables.",
    mamboRead: "A foldable to consider mainly when the discount is serious."
  }),
  recentPhone({
    slug: "samsung-galaxy-z-flip6",
    name: "Samsung Galaxy Z Flip6",
    brand: "Samsung",
    short: "Pocketable flip flagship",
    priceBand: "Foldable",
    released: "2024",
    image: { src: gsmImage("samsung-galaxy-z-flip6"), alt: "Samsung Galaxy Z Flip6 product image" },
    scores: { camera: 7.7, battery: 7.4, performance: 9.0, longevity: 8.4, value: 6.4 },
    benchmarks: {
      antutu: "1.8M to 2.0M class",
      geekbench: "2,200 single, 6,800 multi class",
      pcmark: "Work 3.0 flagship foldable class",
      threeDMark: "Wild Life Extreme flagship class",
      note: "Compact foldables throttle differently from large slab phones."
    },
    display: "Inner folding AMOLED plus cover screen",
    chipset: "Snapdragon 8 Gen 3 for Galaxy class",
    memory: "12GB RAM class",
    storage: "256GB or 512GB",
    rearCamera: "Dual camera system",
    frontCamera: "10MP class",
    battery: "4,000mAh class",
    charging: "25W wired class plus wireless",
    durability: "IP48 class on supported model",
    software: "One UI with Flex Mode features",
    weight: "Around 187g",
    extras: "Pocketable design, cover screen widgets",
    bestFor: "People who want a compact phone with personality.",
    watchOut: "Battery and camera versatility trail slab flagships.",
    mamboRead: "A style and portability phone first, with flagship speed inside."
  }),
  recentPhone({
    slug: "iphone-15",
    name: "iPhone 15",
    brand: "Apple",
    short: "Mainstream USB-C iPhone",
    priceBand: "Premium",
    released: "2023",
    image: { src: gsmImage("apple-iphone-15"), alt: "iPhone 15 product image" },
    scores: { camera: 8.2, battery: 7.6, performance: 8.7, longevity: 8.9, value: 7.2 },
    benchmarks: {
      antutu: "1.3M to 1.5M class",
      geekbench: "2,500 single, 6,300 multi class",
      pcmark: "Not applicable on iOS",
      threeDMark: "High-end iOS GPU class",
      note: "A16 Bionic remains fast for mainstream use."
    },
    display: "6.1-inch OLED, 60Hz",
    chipset: "Apple A16 Bionic class",
    memory: "Apple does not market RAM prominently",
    storage: "128GB to 512GB",
    rearCamera: "48MP main plus ultrawide",
    frontCamera: "12MP TrueDepth class",
    battery: "All-day class",
    charging: "USB-C wired and MagSafe wireless",
    durability: "IP68 class",
    software: "iOS with long update support",
    weight: "Around 171g",
    extras: "USB-C, Dynamic Island, good resale",
    bestFor: "People who want a modern iPhone at a more reachable price.",
    watchOut: "The 60Hz screen feels dated beside cheaper Android phones.",
    mamboRead: "A sensible iPhone if Pro features are not needed."
  })
  ,
  recentPhone({
    slug: "samsung-galaxy-s25",
    name: "Samsung Galaxy S25",
    brand: "Samsung",
    short: "Compact Galaxy flagship",
    priceBand: "Premium",
    released: "2025",
    image: { src: gsmImage("samsung-galaxy-s25-sm-s931"), alt: "Samsung Galaxy S25 product image" },
    scores: { camera: 8.6, battery: 7.7, performance: 9.4, longevity: 9.5, value: 7.3 },
    benchmarks: { antutu: "2.3M to 2.7M class", geekbench: "2,900 single, 9,000 multi class", pcmark: "Work 3.0 elite Android class", threeDMark: "Wild Life Extreme elite class", note: "Compact body thermals can differ from Ultra models." },
    display: "Compact LTPO AMOLED, adaptive high refresh rate",
    chipset: "Snapdragon 8 Elite for Galaxy class",
    memory: "12GB RAM class, market dependent",
    storage: "128GB to 512GB class",
    rearCamera: "Triple camera with main, ultrawide, and telephoto",
    frontCamera: "12MP class",
    battery: "4,000mAh class",
    charging: "25W wired class plus wireless",
    durability: "IP68 class",
    software: "One UI with long update support",
    weight: "Compact flagship class",
    extras: "Galaxy AI, small flagship size",
    bestFor: "People who want flagship Android speed in a smaller body.",
    watchOut: "Battery and charging are less dramatic than larger rivals.",
    mamboRead: "A compact flagship for buyers who dislike huge phones."
  }),
  recentPhone({
    slug: "iphone-16e",
    name: "iPhone 16e",
    brand: "Apple",
    short: "Lower-cost modern iPhone",
    priceBand: "Premium",
    released: "2025",
    image: { src: gsmImage("apple-iphone-16e"), alt: "iPhone 16e product image" },
    scores: { camera: 7.8, battery: 8.0, performance: 8.9, longevity: 9.1, value: 7.4 },
    benchmarks: { antutu: "1.5M to 1.7M class", geekbench: "3,000 single, 7,500 multi class", pcmark: "Not applicable on iOS", threeDMark: "High-end iOS GPU class", note: "iOS scores are not directly comparable with Android totals." },
    display: "OLED, mainstream iPhone size",
    chipset: "Apple A18 class",
    memory: "Apple does not market RAM prominently",
    storage: "128GB to 512GB class",
    rearCamera: "Single main camera system",
    frontCamera: "TrueDepth selfie camera class",
    battery: "All-day iPhone class",
    charging: "USB-C wired charging",
    durability: "IP rating on supported model",
    software: "iOS with long update support",
    weight: "Light iPhone class",
    extras: "Apple ecosystem, long updates, simpler camera setup",
    bestFor: "People who want a newer iPhone without Pro pricing.",
    watchOut: "Camera versatility and display features are cut back.",
    mamboRead: "A practical iPhone if ecosystem and support matter more than Pro extras."
  }),
  recentPhone({
    slug: "oppo-find-x8-pro",
    name: "Oppo Find X8 Pro",
    brand: "Oppo",
    short: "Camera-rich Android flagship",
    priceBand: "Premium",
    released: "2024",
    image: { src: gsmImage("oppo-find-x8-pro"), alt: "Oppo Find X8 Pro product image" },
    scores: { camera: 9.0, battery: 8.8, performance: 9.2, longevity: 8.0, value: 7.3 },
    benchmarks: { antutu: "2.4M to 2.8M class", geekbench: "2,800 single, 8,400 multi class", pcmark: "Work 3.0 elite Android class", threeDMark: "Flagship GPU class", note: "Dimensity flagship scores vary by cooling and performance mode." },
    display: "Large LTPO AMOLED, high refresh rate",
    chipset: "MediaTek Dimensity 9400 class",
    memory: "12GB or 16GB RAM class",
    storage: "256GB to 1TB class",
    rearCamera: "Triple or quad Hasselblad-tuned flagship camera system",
    frontCamera: "32MP class",
    battery: "Large battery class",
    charging: "Very fast wired plus wireless charging",
    durability: "IP68 or IP69 class",
    software: "Android with ColorOS",
    weight: "Around 215g class",
    extras: "Strong zoom camera, fast charging, flagship MediaTek chip",
    bestFor: "Camera-first Android buyers comparing beyond Samsung and Xiaomi.",
    watchOut: "Local availability and software taste matter.",
    mamboRead: "A serious flagship alternative with strong camera hardware."
  }),
  recentPhone({
    slug: "vivo-x200-pro",
    name: "Vivo X200 Pro",
    brand: "Vivo",
    short: "ZEISS camera flagship",
    priceBand: "Premium",
    released: "2024",
    image: { src: gsmImage("vivo-x200-pro"), alt: "Vivo X200 Pro product image" },
    scores: { camera: 9.2, battery: 8.8, performance: 9.2, longevity: 7.9, value: 7.2 },
    benchmarks: { antutu: "2.4M to 2.8M class", geekbench: "2,800 single, 8,400 multi class", pcmark: "Work 3.0 elite Android class", threeDMark: "Flagship GPU class", note: "Camera processing and performance mode can affect heat and scores." },
    display: "Large LTPO AMOLED, high refresh rate",
    chipset: "MediaTek Dimensity 9400 class",
    memory: "12GB or 16GB RAM class",
    storage: "256GB to 1TB class",
    rearCamera: "ZEISS-tuned triple camera with telephoto focus",
    frontCamera: "32MP class",
    battery: "Large silicon-carbon battery class",
    charging: "Fast wired plus wireless charging",
    durability: "IP68 or IP69 class",
    software: "Android with Vivo software, market dependent",
    weight: "Around 220g class",
    extras: "ZEISS portrait tools, strong zoom, large battery",
    bestFor: "People who want portrait and zoom photography as a top priority.",
    watchOut: "Global software and availability vary by region.",
    mamboRead: "A camera enthusiast phone with real flagship power."
  }),
  recentPhone({
    slug: "honor-magic7-pro",
    name: "Honor Magic7 Pro",
    brand: "Honor",
    short: "Battery-heavy camera flagship",
    priceBand: "Premium",
    released: "2025",
    image: { src: gsmImage("honor-magic7-pro"), alt: "Honor Magic7 Pro product image" },
    scores: { camera: 8.9, battery: 9.0, performance: 9.5, longevity: 8.0, value: 7.3 },
    benchmarks: { antutu: "2.5M to 2.9M class", geekbench: "3,000 single, 9,000 multi class", pcmark: "Work 3.0 elite Android class", threeDMark: "Wild Life Extreme elite class", note: "Snapdragon Elite performance can vary by thermal profile." },
    display: "Large LTPO OLED, high refresh rate",
    chipset: "Snapdragon 8 Elite class",
    memory: "12GB or 16GB RAM class",
    storage: "256GB to 1TB class",
    rearCamera: "Triple flagship camera system with telephoto",
    frontCamera: "High-resolution selfie and depth hardware, market dependent",
    battery: "Large silicon-carbon battery class",
    charging: "Fast wired plus wireless charging",
    durability: "Flagship ingress protection class",
    software: "Android with MagicOS",
    weight: "Large flagship class",
    extras: "Battery endurance, AI features, strong camera hardware",
    bestFor: "Buyers who want a premium Android alternative with big battery focus.",
    watchOut: "Check local support, warranty, and software preference.",
    mamboRead: "A high-spec flagship that deserves a look outside the usual two brands."
  }),
  recentPhone({
    slug: "realme-gt-7-pro",
    name: "Realme GT 7 Pro",
    brand: "Realme",
    short: "Value performance flagship",
    priceBand: "Premium",
    released: "2024",
    image: { src: gsmImage("realme-gt7-pro"), alt: "Realme GT 7 Pro product image" },
    scores: { camera: 7.8, battery: 9.1, performance: 9.5, longevity: 7.6, value: 8.1 },
    benchmarks: { antutu: "2.5M to 2.9M class", geekbench: "3,000 single, 9,000 multi class", pcmark: "Work 3.0 elite Android class", threeDMark: "Wild Life Extreme elite class", note: "Often tuned for high benchmark output and fast charging." },
    display: "Large LTPO AMOLED, high refresh rate",
    chipset: "Snapdragon 8 Elite class",
    memory: "12GB or 16GB RAM class",
    storage: "256GB to 1TB class",
    rearCamera: "Triple camera system with periscope on supported model",
    frontCamera: "16MP class",
    battery: "Large battery class",
    charging: "Very fast wired charging",
    durability: "High ingress protection on supported model",
    software: "Android with Realme UI",
    weight: "Around 220g class",
    extras: "Fast chip, fast charging, aggressive pricing",
    bestFor: "People who want flagship speed for less than premium brand pricing.",
    watchOut: "Camera and software polish are not the safest part of the package.",
    mamboRead: "A benchmark and battery beast if the price is sharp."
  }),
  recentPhone({
    slug: "nothing-phone-3",
    name: "Nothing Phone 3",
    brand: "Nothing",
    short: "Design-led premium Nothing phone",
    priceBand: "Premium",
    released: "2025",
    image: { src: gsmImage("nothing-phone-3"), alt: "Nothing Phone 3 product image" },
    scores: { camera: 8.0, battery: 8.1, performance: 8.6, longevity: 8.0, value: 7.5 },
    benchmarks: { antutu: "1.5M plus class", geekbench: "2,000 plus single, 6,000 plus multi class", pcmark: "Work 3.0 upper flagship class", threeDMark: "Upper flagship GPU class", note: "Scores depend on final chipset and performance mode." },
    display: "OLED, high refresh rate",
    chipset: "Upper flagship Snapdragon class",
    memory: "12GB RAM class",
    storage: "256GB to 512GB class",
    rearCamera: "Multi-camera system",
    frontCamera: "High-resolution selfie camera",
    battery: "5,000mAh class",
    charging: "Fast wired charging, wireless on supported variant",
    durability: "IP rating on supported model",
    software: "Nothing OS on Android",
    weight: "Mid to large phone class",
    extras: "Distinctive interface, design-led software, Glyph-style features",
    bestFor: "People who want a cleaner Android personality without buying Pixel.",
    watchOut: "Camera consistency should be checked against bigger flagship brands.",
    mamboRead: "A phone for buyers who want their device to feel different."
  }),
  recentPhone({
    slug: "xiaomi-15",
    name: "Xiaomi 15",
    brand: "Xiaomi",
    short: "Compact Xiaomi flagship",
    priceBand: "Premium",
    released: "2024",
    image: { src: gsmImage("xiaomi-15"), alt: "Xiaomi 15 product image" },
    scores: { camera: 8.5, battery: 8.5, performance: 9.5, longevity: 7.8, value: 7.8 },
    benchmarks: { antutu: "2.5M to 2.9M class", geekbench: "3,000 single, 9,000 multi class", pcmark: "Work 3.0 elite Android class", threeDMark: "Wild Life Extreme elite class", note: "Compact flagship thermals can limit sustained loads." },
    display: "Compact LTPO OLED, high refresh rate",
    chipset: "Snapdragon 8 Elite class",
    memory: "12GB or 16GB RAM class",
    storage: "256GB to 1TB class",
    rearCamera: "Leica-tuned triple camera system",
    frontCamera: "32MP class",
    battery: "Large compact-flagship battery class",
    charging: "Fast wired plus wireless charging",
    durability: "IP68 class",
    software: "Android with HyperOS",
    weight: "Compact flagship class",
    extras: "Small flagship design, Leica camera tuning, fast charging",
    bestFor: "People who want flagship power without a huge phone.",
    watchOut: "Regional software and warranty should be checked carefully.",
    mamboRead: "A compact Android flagship with serious speed."
  }),
  recentPhone({
    slug: "samsung-galaxy-z-fold7",
    name: "Samsung Galaxy Z Fold7",
    brand: "Samsung",
    short: "Latest Samsung book-style foldable",
    priceBand: "Foldable",
    released: "2025",
    image: { src: gsmImage("samsung-galaxy-z-fold7"), alt: "Samsung Galaxy Z Fold7 product image" },
    scores: { camera: 8.2, battery: 7.7, performance: 9.4, longevity: 8.8, value: 5.9 },
    benchmarks: { antutu: "2.3M to 2.8M class", geekbench: "2,900 single, 9,000 multi class", pcmark: "Work 3.0 elite foldable class", threeDMark: "Flagship GPU class", note: "Thin foldables can score differently under sustained load." },
    display: "Outer screen plus large inner folding AMOLED",
    chipset: "Snapdragon flagship for Galaxy class",
    memory: "12GB RAM class",
    storage: "256GB to 1TB class",
    rearCamera: "Multi-camera foldable system",
    frontCamera: "Cover and inner selfie cameras",
    battery: "Foldable battery class",
    charging: "Wired plus wireless charging",
    durability: "Foldable ingress protection class",
    software: "One UI with foldable multitasking",
    weight: "Large foldable class",
    extras: "Tablet-like inner display, Galaxy AI, productivity tools",
    bestFor: "People who genuinely use a phone as a small tablet.",
    watchOut: "High price and repair costs matter.",
    mamboRead: "A productivity phone first, luxury gadget second."
  }),
  recentPhone({
    slug: "samsung-galaxy-z-flip7",
    name: "Samsung Galaxy Z Flip7",
    brand: "Samsung",
    short: "Latest pocketable Samsung foldable",
    priceBand: "Foldable",
    released: "2025",
    image: { src: gsmImage("samsung-galaxy-z-flip7"), alt: "Samsung Galaxy Z Flip7 product image" },
    scores: { camera: 7.8, battery: 7.7, performance: 9.1, longevity: 8.7, value: 6.3 },
    benchmarks: { antutu: "1.8M to 2.5M class", geekbench: "2,200 plus single, 6,500 plus multi class", pcmark: "Work 3.0 flagship foldable class", threeDMark: "Flagship GPU class", note: "Compact foldable cooling affects long gaming sessions." },
    display: "Inner folding AMOLED plus cover display",
    chipset: "Flagship Galaxy foldable chipset class",
    memory: "12GB RAM class",
    storage: "256GB or 512GB class",
    rearCamera: "Dual camera system",
    frontCamera: "Selfie camera class",
    battery: "Compact foldable battery class",
    charging: "Wired plus wireless charging",
    durability: "Foldable ingress protection class",
    software: "One UI with cover screen features",
    weight: "Pocketable foldable class",
    extras: "Compact fold, cover widgets, Flex Mode",
    bestFor: "People who want portability and style over maximum camera hardware.",
    watchOut: "Battery and zoom are weaker than slab flagships.",
    mamboRead: "A lifestyle foldable that makes most sense if the shape delights you."
  }),
  recentPhone({
    slug: "iphone-17-pro-max",
    name: "iPhone 17 Pro Max",
    brand: "Apple",
    short: "Largest current Pro iPhone",
    priceBand: "Premium",
    released: "2025",
    image: { src: gsmImage("apple-iphone-17-pro-max"), alt: "iPhone 17 Pro Max product image" },
    scores: { camera: 9.4, battery: 9.0, performance: 9.7, longevity: 9.5, value: 6.6 },
    benchmarks: { antutu: "2.1M to 2.4M class", geekbench: "3,700 single, 9,600 multi class", pcmark: "Not applicable on iOS", threeDMark: "Elite iOS GPU class", note: "A19 Pro scores are not directly comparable with Android benchmark totals." },
    display: "6.9-inch Super Retina XDR OLED, ProMotion up to 120Hz",
    chipset: "Apple A19 Pro class",
    memory: "Apple does not market RAM prominently",
    storage: "256GB to 2TB class",
    rearCamera: "Triple 48MP Fusion camera system",
    frontCamera: "18MP Center Stage camera",
    battery: "Longest iPhone battery life class",
    charging: "USB-C, MagSafe, and Qi2 wireless charging",
    durability: "IP68 class",
    software: "iOS 26 with long update support",
    weight: "Around 231g",
    extras: "Best iPhone camera package, large display, strong video",
    bestFor: "People who want the strongest current iPhone for camera, battery, and video.",
    watchOut: "Very expensive and large in the hand.",
    mamboRead: "The iPhone to compare against every top flagship in 2026."
  }),
  recentPhone({
    slug: "iphone-17-pro",
    name: "iPhone 17 Pro",
    brand: "Apple",
    short: "Current Pro iPhone in the smaller size",
    priceBand: "Premium",
    released: "2025",
    image: { src: gsmImage("apple-iphone-17-pro"), alt: "iPhone 17 Pro product image" },
    scores: { camera: 9.2, battery: 8.3, performance: 9.7, longevity: 9.5, value: 6.9 },
    benchmarks: { antutu: "2.1M to 2.4M class", geekbench: "3,700 single, 9,500 multi class", pcmark: "Not applicable on iOS", threeDMark: "Elite iOS GPU class", note: "Smaller body can affect sustained performance under long loads." },
    display: "6.3-inch Super Retina XDR OLED, ProMotion up to 120Hz",
    chipset: "Apple A19 Pro class",
    memory: "Apple does not market RAM prominently",
    storage: "256GB to 1TB class",
    rearCamera: "Triple 48MP Fusion camera system",
    frontCamera: "18MP Center Stage camera",
    battery: "All-day Pro iPhone class",
    charging: "USB-C, MagSafe, and Qi2 wireless charging",
    durability: "IP68 class",
    software: "iOS 26 with long update support",
    weight: "Around 204g",
    extras: "Pro camera tools, compact Pro footprint, strong video",
    bestFor: "People who want Pro iPhone cameras without the Max size.",
    watchOut: "Battery is not as strong as the Pro Max.",
    mamboRead: "The more pocketable serious iPhone."
  }),
  recentPhone({
    slug: "iphone-17",
    name: "iPhone 17",
    brand: "Apple",
    short: "Mainstream current iPhone",
    priceBand: "Premium",
    released: "2025",
    image: { src: gsmImage("apple-iphone-17"), alt: "iPhone 17 product image" },
    scores: { camera: 8.5, battery: 8.1, performance: 9.2, longevity: 9.4, value: 7.5 },
    benchmarks: { antutu: "1.8M to 2.1M class", geekbench: "3,400 single, 8,600 multi class", pcmark: "Not applicable on iOS", threeDMark: "High-end iOS GPU class", note: "Base iPhone finally gets 120Hz, making older 60Hz models less attractive." },
    display: "6.3-inch Super Retina XDR OLED, ProMotion up to 120Hz",
    chipset: "Apple A19 class",
    memory: "Apple does not market RAM prominently",
    storage: "256GB or 512GB",
    rearCamera: "48MP Dual Fusion camera system",
    frontCamera: "18MP Center Stage camera",
    battery: "All-day iPhone class",
    charging: "USB-C, MagSafe, and Qi2 wireless charging",
    durability: "IP68 class",
    software: "iOS 26 with long update support",
    weight: "177g",
    extras: "120Hz display, Apple ecosystem, strong resale",
    bestFor: "Most people who want a current iPhone without Pro pricing.",
    watchOut: "No dedicated Pro telephoto camera.",
    mamboRead: "The sensible default iPhone for 2026 buyers."
  }),
  recentPhone({
    slug: "iphone-air",
    name: "iPhone Air",
    brand: "Apple",
    short: "Ultra-thin iPhone in the 17 generation",
    priceBand: "Premium",
    released: "2025",
    image: { src: gsmImage("apple-iphone-air"), alt: "iPhone Air product image" },
    scores: { camera: 7.9, battery: 7.5, performance: 9.3, longevity: 9.2, value: 6.8 },
    benchmarks: { antutu: "1.9M to 2.2M class", geekbench: "3,500 single, 9,000 multi class", pcmark: "Not applicable on iOS", threeDMark: "High-end iOS GPU class", note: "Thin design prioritizes feel and portability over camera versatility." },
    display: "6.5-inch Super Retina XDR OLED, ProMotion up to 120Hz",
    chipset: "Apple A19 Pro class",
    memory: "Apple does not market RAM prominently",
    storage: "256GB to 1TB",
    rearCamera: "Single 48MP Fusion camera",
    frontCamera: "18MP Center Stage camera",
    battery: "All-day class, helped by slim-pack optimization",
    charging: "USB-C, MagSafe, and Qi2 wireless charging",
    durability: "IP68 class",
    software: "iOS 26 with long update support",
    weight: "165g",
    extras: "Very thin body, titanium design, lightweight feel",
    bestFor: "People who care about thinness and comfort more than camera variety.",
    watchOut: "Single rear camera is limiting at this price.",
    mamboRead: "The design-first iPhone, not the camera-first iPhone."
  }),
  recentPhone({
    slug: "samsung-galaxy-s26-plus",
    name: "Samsung Galaxy S26+",
    brand: "Samsung",
    short: "Large Galaxy flagship without the S Pen",
    priceBand: "Premium",
    released: "2026",
    image: { src: gsmImage("samsung-galaxy-s26-plus"), alt: "Samsung Galaxy S26 Plus product image" },
    scores: { camera: 8.6, battery: 8.6, performance: 9.5, longevity: 9.5, value: 7.2 },
    benchmarks: { antutu: "2.7M to 3.1M class", geekbench: "3,100 single, 9,300 multi class", pcmark: "Work 3.0 elite Android class", threeDMark: "Elite Android GPU class", note: "Snapdragon and Exynos market variants can differ." },
    display: "6.7-inch QHD+ Dynamic AMOLED 2X, 120Hz",
    chipset: "Snapdragon 8 Elite Gen 5 or Exynos 2600 class, market dependent",
    memory: "12GB RAM class",
    storage: "256GB or 512GB",
    rearCamera: "Triple camera with main, ultrawide, and telephoto",
    frontCamera: "12MP class",
    battery: "4,900mAh class",
    charging: "Fast wired plus wireless charging",
    durability: "IP68 class",
    software: "One UI 8.5 with seven-year support class",
    weight: "190g",
    extras: "Galaxy AI, large display, lighter than Ultra",
    bestFor: "People who want a big Samsung flagship but do not need the Ultra camera or S Pen.",
    watchOut: "Ultra still wins on zoom and productivity features.",
    mamboRead: "The practical large Galaxy flagship."
  }),
  recentPhone({
    slug: "samsung-galaxy-s26",
    name: "Samsung Galaxy S26",
    brand: "Samsung",
    short: "Compact current Galaxy flagship",
    priceBand: "Premium",
    released: "2026",
    image: { src: gsmImage("samsung-galaxy-s26"), alt: "Samsung Galaxy S26 product image" },
    scores: { camera: 8.4, battery: 8.0, performance: 9.4, longevity: 9.5, value: 7.5 },
    benchmarks: { antutu: "2.7M to 3.1M class", geekbench: "3,100 single, 9,300 multi class", pcmark: "Work 3.0 elite Android class", threeDMark: "Elite Android GPU class", note: "Compact body and regional chipset affect sustained scores." },
    display: "6.3-inch FHD+ Dynamic AMOLED 2X, 120Hz",
    chipset: "Snapdragon 8 Elite Gen 5 or Exynos 2600 class, market dependent",
    memory: "12GB RAM class",
    storage: "256GB or 512GB",
    rearCamera: "Triple camera with main, ultrawide, and telephoto",
    frontCamera: "12MP class",
    battery: "4,300mAh class",
    charging: "Fast wired plus wireless charging",
    durability: "IP68 class",
    software: "One UI 8.5 with seven-year support class",
    weight: "167g",
    extras: "Galaxy AI, compact size, long support",
    bestFor: "People who want Samsung's current flagship in a smaller body.",
    watchOut: "Smaller battery and less advanced camera hardware than Ultra.",
    mamboRead: "The easiest Galaxy S26 to live with day to day."
  }),
  recentPhone({
    slug: "google-pixel-10-pro-xl",
    name: "Google Pixel 10 Pro XL",
    brand: "Google",
    short: "Largest current Pixel flagship",
    priceBand: "Premium",
    released: "2025",
    image: { src: gsmImage("google-pixel-10-pro-xl-"), alt: "Google Pixel 10 Pro XL product image" },
    scores: { camera: 9.1, battery: 8.0, performance: 8.5, longevity: 9.4, value: 7.0 },
    benchmarks: { antutu: "1.4M to 1.7M class", geekbench: "2,000 single, 5,300 multi class", pcmark: "Work 3.0 upper-flagship class", threeDMark: "Below fastest Snapdragon and Apple GPU tiers", note: "Tensor G5 emphasizes AI features more than peak gaming scores." },
    display: "6.8-inch OLED, 120Hz class",
    chipset: "Google Tensor G5 class",
    memory: "16GB RAM class",
    storage: "256GB to 1TB",
    rearCamera: "Triple Pixel camera system with telephoto",
    frontCamera: "High-resolution selfie camera",
    battery: "5,200mAh class",
    charging: "Fast wired plus Pixelsnap wireless charging",
    durability: "IP68 class",
    software: "Pixel Android 16 with seven-year support class",
    weight: "Around 232g",
    extras: "Pixel AI, clean Android, strong still photos",
    bestFor: "People who want the largest Pixel and Google's newest AI tools.",
    watchOut: "Raw gaming performance is behind the fastest rivals.",
    mamboRead: "The Pixel for camera, AI, and software-first buyers."
  }),
  recentPhone({
    slug: "google-pixel-10-pro",
    name: "Google Pixel 10 Pro",
    brand: "Google",
    short: "Smaller current Pixel Pro",
    priceBand: "Premium",
    released: "2025",
    image: { src: gsmImage("google-pixel-10-pro-"), alt: "Google Pixel 10 Pro product image" },
    scores: { camera: 9.0, battery: 7.7, performance: 8.4, longevity: 9.4, value: 7.1 },
    benchmarks: { antutu: "1.4M to 1.7M class", geekbench: "2,000 single, 5,300 multi class", pcmark: "Work 3.0 upper-flagship class", threeDMark: "Below fastest Snapdragon and Apple GPU tiers", note: "Smaller body can run warmer during long camera or gaming sessions." },
    display: "6.3-inch OLED, 120Hz class",
    chipset: "Google Tensor G5 class",
    memory: "16GB RAM class",
    storage: "128GB to 1TB, market dependent",
    rearCamera: "Triple Pixel camera system with telephoto",
    frontCamera: "High-resolution selfie camera",
    battery: "Pro Pixel battery class",
    charging: "Fast wired plus Pixelsnap wireless charging",
    durability: "IP68 class",
    software: "Pixel Android 16 with seven-year support class",
    weight: "Around 207g",
    extras: "Pixel AI, Pro camera controls, compact Pro size",
    bestFor: "People who want Pixel Pro cameras without the XL size.",
    watchOut: "Battery is not as comfortable as the XL.",
    mamboRead: "The balanced Pixel Pro for software-first buyers."
  }),
  recentPhone({
    slug: "google-pixel-10",
    name: "Google Pixel 10",
    brand: "Google",
    short: "Mainstream current Pixel",
    priceBand: "Premium",
    released: "2025",
    image: { src: gsmImage("google-pixel-10-"), alt: "Google Pixel 10 product image" },
    scores: { camera: 8.4, battery: 7.8, performance: 8.3, longevity: 9.4, value: 7.6 },
    benchmarks: { antutu: "1.3M to 1.6M class", geekbench: "2,000 single, 5,200 multi class", pcmark: "Work 3.0 upper-flagship class", threeDMark: "Below fastest Snapdragon and Apple GPU tiers", note: "Tensor G5 is quick for daily use, less dominant in GPU-heavy tests." },
    display: "6.3-inch OLED, 120Hz class",
    chipset: "Google Tensor G5 class",
    memory: "12GB RAM class",
    storage: "128GB or 256GB",
    rearCamera: "Triple camera system, including telephoto on this generation",
    frontCamera: "10.5MP class",
    battery: "4,970mAh class",
    charging: "Fast wired plus Pixelsnap wireless charging",
    durability: "IP68 class",
    software: "Pixel Android 16 with seven-year support class",
    weight: "Mainstream Pixel class",
    extras: "Pixel AI, clean Android, improved camera flexibility",
    bestFor: "Most Android buyers who want Pixel software without Pro pricing.",
    watchOut: "Pro models have stronger camera hardware and displays.",
    mamboRead: "The sensible Pixel 10 choice."
  }),
  recentPhone({
    slug: "google-pixel-10a",
    name: "Google Pixel 10a",
    brand: "Google",
    short: "Current affordable Pixel",
    priceBand: "Midrange",
    released: "2026",
    image: { src: gsmImage("google-pixel-10a"), alt: "Google Pixel 10a product image" },
    scores: { camera: 8.0, battery: 8.2, performance: 7.5, longevity: 9.2, value: 8.4 },
    benchmarks: { antutu: "900K to 1.1M class", geekbench: "1,700 single, 4,300 multi class", pcmark: "Work 3.0 upper-mid class", threeDMark: "Below flagship GPU tier", note: "Uses a previous-generation Tensor class chip but keeps Pixel software strengths." },
    display: "6.3-inch Actua pOLED, 120Hz class",
    chipset: "Google Tensor G4 class",
    memory: "8GB RAM class",
    storage: "128GB or 256GB",
    rearCamera: "48MP wide plus 13MP ultrawide",
    frontCamera: "13MP class",
    battery: "5,100mAh class",
    charging: "Wired plus wireless charging",
    durability: "IP68 class",
    software: "Pixel Android 16 with seven-year support class",
    weight: "Around 185g class",
    extras: "Pixel camera processing, long updates, lower price",
    bestFor: "People who want Pixel photos and software at a lower price.",
    watchOut: "Performance is not flagship-level.",
    mamboRead: "A very strong midrange pick if Pixel features matter."
  }),
  recentPhone({
    slug: "xiaomi-17-ultra",
    name: "Xiaomi 17 Ultra",
    brand: "Xiaomi",
    short: "2026 Leica camera flagship",
    priceBand: "Premium",
    released: "2026",
    image: { src: gsmImage("xiaomi-17-ultra"), alt: "Xiaomi 17 Ultra product image" },
    scores: { camera: 9.4, battery: 8.7, performance: 9.6, longevity: 8.0, value: 7.2 },
    benchmarks: { antutu: "3.0M plus class", geekbench: "3,100 single, 9,500 multi class", pcmark: "Work 3.0 elite Android class", threeDMark: "Elite Android GPU class", note: "Camera grip modes and performance profiles can change behavior." },
    display: "Large LTPO AMOLED, high refresh rate",
    chipset: "Snapdragon 8 Elite Gen 5 class",
    memory: "16GB RAM class",
    storage: "512GB to 1TB class",
    rearCamera: "Leica-tuned flagship multi-camera system",
    frontCamera: "High-resolution selfie camera",
    battery: "Large flagship battery class",
    charging: "Very fast wired plus wireless charging",
    durability: "IP68 or IP69 class",
    software: "Android with HyperOS",
    weight: "Large camera flagship class",
    extras: "Leica camera tuning, pro camera accessories, large sensor focus",
    bestFor: "People who want one of the most camera-heavy Android phones available.",
    watchOut: "Import status and software preferences matter.",
    mamboRead: "A camera-first rival to Galaxy Ultra and iPhone Pro Max."
  }),
  recentPhone({
    slug: "oppo-find-x9-pro",
    name: "Oppo Find X9 Pro",
    brand: "Oppo",
    short: "2026 Oppo flagship camera phone",
    priceBand: "Premium",
    released: "2026",
    image: { src: gsmImage("oppo-find-x9-pro"), alt: "Oppo Find X9 Pro product image" },
    scores: { camera: 9.2, battery: 8.8, performance: 9.5, longevity: 8.0, value: 7.2 },
    benchmarks: { antutu: "3.0M class", geekbench: "3,000 single, 9,000 multi class", pcmark: "Work 3.0 elite Android class", threeDMark: "Elite Android GPU class", note: "Scores vary by chipset region and performance profile." },
    display: "Large LTPO AMOLED, high refresh rate",
    chipset: "2026 flagship Android chipset class",
    memory: "12GB or 16GB RAM class",
    storage: "256GB to 1TB class",
    rearCamera: "Hasselblad-tuned flagship camera system",
    frontCamera: "High-resolution selfie camera",
    battery: "Large silicon-carbon battery class",
    charging: "Very fast wired plus wireless charging",
    durability: "High IP rating on supported variants",
    software: "Android with ColorOS",
    weight: "Large flagship class",
    extras: "Camera tuning, large battery, premium display",
    bestFor: "Buyers cross-shopping Chinese camera flagships.",
    watchOut: "Local availability and warranty are key.",
    mamboRead: "A serious camera flagship for markets where Oppo support is strong."
  }),
  recentPhone({
    slug: "honor-magic8-pro",
    name: "Honor Magic8 Pro",
    brand: "Honor",
    short: "2026 Honor camera and battery flagship",
    priceBand: "Premium",
    released: "2026",
    image: { src: gsmImage("honor-magic8-pro"), alt: "Honor Magic8 Pro product image" },
    scores: { camera: 9.1, battery: 9.1, performance: 9.6, longevity: 8.1, value: 7.4 },
    benchmarks: { antutu: "3.0M plus class", geekbench: "3,100 single, 9,500 multi class", pcmark: "Work 3.0 elite Android class", threeDMark: "Elite Android GPU class", note: "Big battery and cooling help sustained performance, but modes vary." },
    display: "Large OLED, high refresh rate",
    chipset: "Snapdragon 8 Elite Gen 5 class",
    memory: "12GB or 16GB RAM class",
    storage: "256GB to 1TB class",
    rearCamera: "Flagship multi-camera system with high-resolution telephoto",
    frontCamera: "High-resolution selfie camera",
    battery: "Very large silicon-carbon battery class",
    charging: "Fast wired plus wireless charging",
    durability: "Premium ingress protection class",
    software: "Android with MagicOS",
    weight: "Large flagship class",
    extras: "Big battery, strong zoom, high performance",
    bestFor: "People who want huge battery specs with flagship speed.",
    watchOut: "Brand support and resale vary by market.",
    mamboRead: "A spec-heavy flagship that belongs in serious comparisons."
  }),
  recentPhone({
    slug: "tecno-camon-50-pro",
    name: "Tecno Camon 50 Pro",
    brand: "Tecno",
    short: "2026 camera-focused Tecno midrange phone",
    priceBand: "Midrange",
    released: "2026",
    image: { src: gsmImage("tecno-camon-50-pro"), alt: "Tecno Camon 50 Pro product image" },
    scores: { camera: 7.5, battery: 8.4, performance: 7.1, longevity: 6.8, value: 8.2 },
    benchmarks: { antutu: "650K to 900K class", geekbench: "1,000 single, 3,000 multi class", pcmark: "Work 3.0 midrange class", threeDMark: "Midrange GPU class", note: "Exact chipset and camera hardware can vary by market variant." },
    display: "Large AMOLED or high-refresh display, variant dependent",
    chipset: "Upper-mid MediaTek class, market dependent",
    memory: "8GB or 12GB RAM class",
    storage: "256GB class",
    rearCamera: "Camera-focused multi-camera system",
    frontCamera: "High-resolution selfie camera",
    battery: "5,000mAh plus class",
    charging: "Fast wired charging",
    durability: "Everyday durability, variant dependent",
    software: "Android with Tecno HiOS",
    weight: "Midrange large-screen class",
    extras: "Portrait focus, large screen, local value positioning",
    bestFor: "Buyers who want camera features at a lower price in Tecno-heavy markets.",
    watchOut: "Update support and exact variant should be checked.",
    mamboRead: "A locally relevant midrange camera option."
  })
];

export const phones: PhoneSpec[] = [...starterPhones, ...majorRecentPhones].sort((a, b) => Number(b.released) - Number(a.released) || a.brand.localeCompare(b.brand));
